Repository Azure/terraform-azurerm-avm-ptn-network-private-link-private-dns-zones, pull requests merged in 2025-01, with the labels that each got.

#61 chore: repository governance
  avm
  avm.bat
Labels: Needs: Triage :mag:

#62 feat: update to azurermv4
  README.md
  examples/custom-zones-vnet-link-existing-rg/README.md
  examples/custom-zones-vnet-link-existing-rg/main.tf
  examples/default/README.md
  examples/default/main.tf
  examples/with-vnet-link-existing-rg/README.md
  examples/with-vnet-link-existing-rg/main.tf
  main.tf
  terraform.tf
Labels: Type: Feature Request :heavy_plus_sign:, Type: Hygiene :broom:

#63 feat: add synapse and web pubsub
  README.md
  variables.tf
Labels: Needs: Triage :mag:

#65 feat: additional test and add custom timeouts
  .vscode/settings.json
  README.md
  examples/multi-region-own-vnets-plus-timeouts/README.md
  examples/multi-region-own-vnets-plus-timeouts/_footer.md
  examples/multi-region-own-vnets-plus-timeouts/_header.md
  examples/multi-region-own-vnets-plus-timeouts/main.tf
  examples/multi-region-own-vnets-plus-timeouts/variables.tf
  main.tf
  variables.tf
Labels: Type: Feature Request :heavy_plus_sign:
