Repository Azure/terraform-azurerm-avm-ptn-network-private-link-private-dns-zones, pull requests merged in 2025-05, with the labels that each got.

#81 feat: Add the zone for container apps
  README.md
  variables.tf
Labels: Type: Feature Request :heavy_plus_sign:

#82 feat: allow vnet link name override
  README.md
  examples/with-vnet-link-existing-rg/README.md
  examples/with-vnet-link-existing-rg/main.tf
  locals.tf
  main.tf
  variables.tf
Labels: Needs: Triage :mag:

#84 feat: add customer iterator
  README.md
  examples/with-vnet-link-existing-rg/README.md
  examples/with-vnet-link-existing-rg/main.tf
  locals.tf
  main.tf
  variables.tf
Labels: Needs: Triage :mag:

#86 Allow excluding zones without overriding all zones
  README.md
  examples/exclusions/README.md
  examples/exclusions/_footer.md
  examples/exclusions/_header.md
  examples/exclusions/main.tf
  examples/exclusions/variables.tf
  locals.tf
  variables.tf
Labels: enhancement, Needs: Author Feedback :ear:, Status: External Contribution :earth_africa:, Type: Feature Request :heavy_plus_sign:

#88 feat: Allow excluding zones without overriding all zones (#86)
  README.md
  examples/exclusions/README.md
  examples/exclusions/_footer.md
  examples/exclusions/_header.md
  examples/exclusions/main.tf
  examples/exclusions/variables.tf
  locals.tf
  variables.tf
Labels: enhancement, Type: Feature Request :heavy_plus_sign:
